#!/bin/bash

set -euo pipefail

mkdir -p tmp/repos

ensure_mutagen_local_keys() {
  pushd mutagen-ssh/cmd/mutagen-ssh >/dev/null
  ./generate-development.sh
  popd
}

ensure_mutagen_local_keys

docker compose up "$@"
