#!/bin/bash

set -euo pipefail

mkdir -p backend/tmp/repos

ensure_mutagen_local_keys() {
  pushd backend/cmd/mutagen-ssh >/dev/null
  ./generate-development.sh
  popd
}

ensure_mutagen() {
  echo "⭐ Cloning mutagen (if not exists)"
  [ ! -d "backend/tmp/mutagen/.git" ] && git clone git@github.com:sturdy-dev/mutagen.git backend/tmp/mutagen
  git -C backend/tmp/mutagen fetch

  ensure_mutagen_local_keys
}

ensure_mutagen

docker compose up "$@"
