#!/usr/bin/with-contenv sh

set -euo pipefail

DB_ADDR="postgres://${POSTGRESQL_DB_USER}:${POSTGRESQL_DB_PASS}@${POSTGRESQL_DB_ADDR}/${POSTGRESQL_DB_NAME}?sslmode=disable"

fdmove -c 2 1 \
  api \
  --repos-base-path="${API_REPOS_PATH}" \
  --http-listen-addr="${API_HTTP_ADDR}" \
  --git-listen-addr="${API_GIT_ADDR}" \
  --db="${DB_ADDR}" \
  --production-logger \
  --use-local-queues
