#!/usr/bin/with-contenv sh

set -euo pipefail

fdmove -c 2 1 \
mutagen-ssh \
    --ssh-listen-addr="${MUTAGEN_SSH_ADDR}" \
    --ssh-key-path="${MUTAGEN_SSH_KEY_PATH}" \
    --http-pprof-listen-addr="${MUTAGEN_SSH_HTTPPPROF_LISTEN_ADDR}" \
    --sturdy-api-addr="http://${API_HTTP_ADDR}"
