// Generated by update.go (do not edit)

export type Emoji = {
  name: string
}

export const emojis: Array<Emoji> = [
  {
    name: 'hash',
  },
  {
    name: 'keycap_star',
  },
  {
    name: 'zero',
  },
  {
    name: 'one',
  },
  {
    name: 'two',
  },
  {
    name: 'three',
  },
  {
    name: 'four',
  },
  {
    name: 'five',
  },
  {
    name: 'six',
  },
  {
    name: 'seven',
  },
  {
    name: 'eight',
  },
  {
    name: 'nine',
  },
  {
    name: 'copyright',
  },
  {
    name: 'registered',
  },
  {
    name: 'mahjong',
  },
  {
    name: 'black_joker',
  },
  {
    name: 'a',
  },
  {
    name: 'b',
  },
  {
    name: 'o2',
  },
  {
    name: 'parking',
  },
  {
    name: 'ab',
  },
  {
    name: 'cl',
  },
  {
    name: 'cool',
  },
  {
    name: 'free',
  },
  {
    name: 'id',
  },
  {
    name: 'new',
  },
  {
    name: 'ng',
  },
  {
    name: 'ok',
  },
  {
    name: 'sos',
  },
  {
    name: 'up',
  },
  {
    name: 'vs',
  },
  {
    name: 'flag-ac',
  },
  {
    name: 'flag-ad',
  },
  {
    name: 'flag-ae',
  },
  {
    name: 'flag-af',
  },
  {
    name: 'flag-ag',
  },
  {
    name: 'flag-ai',
  },
  {
    name: 'flag-al',
  },
  {
    name: 'flag-am',
  },
  {
    name: 'flag-ao',
  },
  {
    name: 'flag-aq',
  },
  {
    name: 'flag-ar',
  },
  {
    name: 'flag-as',
  },
  {
    name: 'flag-at',
  },
  {
    name: 'flag-au',
  },
  {
    name: 'flag-aw',
  },
  {
    name: 'flag-ax',
  },
  {
    name: 'flag-az',
  },
  {
    name: 'flag-ba',
  },
  {
    name: 'flag-bb',
  },
  {
    name: 'flag-bd',
  },
  {
    name: 'flag-be',
  },
  {
    name: 'flag-bf',
  },
  {
    name: 'flag-bg',
  },
  {
    name: 'flag-bh',
  },
  {
    name: 'flag-bi',
  },
  {
    name: 'flag-bj',
  },
  {
    name: 'flag-bl',
  },
  {
    name: 'flag-bm',
  },
  {
    name: 'flag-bn',
  },
  {
    name: 'flag-bo',
  },
  {
    name: 'flag-bq',
  },
  {
    name: 'flag-br',
  },
  {
    name: 'flag-bs',
  },
  {
    name: 'flag-bt',
  },
  {
    name: 'flag-bv',
  },
  {
    name: 'flag-bw',
  },
  {
    name: 'flag-by',
  },
  {
    name: 'flag-bz',
  },
  {
    name: 'flag-ca',
  },
  {
    name: 'flag-cc',
  },
  {
    name: 'flag-cd',
  },
  {
    name: 'flag-cf',
  },
  {
    name: 'flag-cg',
  },
  {
    name: 'flag-ch',
  },
  {
    name: 'flag-ci',
  },
  {
    name: 'flag-ck',
  },
  {
    name: 'flag-cl',
  },
  {
    name: 'flag-cm',
  },
  {
    name: 'cn',
  },
  {
    name: 'flag-cn',
  },
  {
    name: 'flag-co',
  },
  {
    name: 'flag-cp',
  },
  {
    name: 'flag-cr',
  },
  {
    name: 'flag-cu',
  },
  {
    name: 'flag-cv',
  },
  {
    name: 'flag-cw',
  },
  {
    name: 'flag-cx',
  },
  {
    name: 'flag-cy',
  },
  {
    name: 'flag-cz',
  },
  {
    name: 'de',
  },
  {
    name: 'flag-de',
  },
  {
    name: 'flag-dg',
  },
  {
    name: 'flag-dj',
  },
  {
    name: 'flag-dk',
  },
  {
    name: 'flag-dm',
  },
  {
    name: 'flag-do',
  },
  {
    name: 'flag-dz',
  },
  {
    name: 'flag-ea',
  },
  {
    name: 'flag-ec',
  },
  {
    name: 'flag-ee',
  },
  {
    name: 'flag-eg',
  },
  {
    name: 'flag-eh',
  },
  {
    name: 'flag-er',
  },
  {
    name: 'es',
  },
  {
    name: 'flag-es',
  },
  {
    name: 'flag-et',
  },
  {
    name: 'flag-eu',
  },
  {
    name: 'flag-fi',
  },
  {
    name: 'flag-fj',
  },
  {
    name: 'flag-fk',
  },
  {
    name: 'flag-fm',
  },
  {
    name: 'flag-fo',
  },
  {
    name: 'fr',
  },
  {
    name: 'flag-fr',
  },
  {
    name: 'flag-ga',
  },
  {
    name: 'gb',
  },
  {
    name: 'uk',
  },
  {
    name: 'flag-gb',
  },
  {
    name: 'flag-gd',
  },
  {
    name: 'flag-ge',
  },
  {
    name: 'flag-gf',
  },
  {
    name: 'flag-gg',
  },
  {
    name: 'flag-gh',
  },
  {
    name: 'flag-gi',
  },
  {
    name: 'flag-gl',
  },
  {
    name: 'flag-gm',
  },
  {
    name: 'flag-gn',
  },
  {
    name: 'flag-gp',
  },
  {
    name: 'flag-gq',
  },
  {
    name: 'flag-gr',
  },
  {
    name: 'flag-gs',
  },
  {
    name: 'flag-gt',
  },
  {
    name: 'flag-gu',
  },
  {
    name: 'flag-gw',
  },
  {
    name: 'flag-gy',
  },
  {
    name: 'flag-hk',
  },
  {
    name: 'flag-hm',
  },
  {
    name: 'flag-hn',
  },
  {
    name: 'flag-hr',
  },
  {
    name: 'flag-ht',
  },
  {
    name: 'flag-hu',
  },
  {
    name: 'flag-ic',
  },
  {
    name: 'flag-id',
  },
  {
    name: 'flag-ie',
  },
  {
    name: 'flag-il',
  },
  {
    name: 'flag-im',
  },
  {
    name: 'flag-in',
  },
  {
    name: 'flag-io',
  },
  {
    name: 'flag-iq',
  },
  {
    name: 'flag-ir',
  },
  {
    name: 'flag-is',
  },
  {
    name: 'it',
  },
  {
    name: 'flag-it',
  },
  {
    name: 'flag-je',
  },
  {
    name: 'flag-jm',
  },
  {
    name: 'flag-jo',
  },
  {
    name: 'jp',
  },
  {
    name: 'flag-jp',
  },
  {
    name: 'flag-ke',
  },
  {
    name: 'flag-kg',
  },
  {
    name: 'flag-kh',
  },
  {
    name: 'flag-ki',
  },
  {
    name: 'flag-km',
  },
  {
    name: 'flag-kn',
  },
  {
    name: 'flag-kp',
  },
  {
    name: 'kr',
  },
  {
    name: 'flag-kr',
  },
  {
    name: 'flag-kw',
  },
  {
    name: 'flag-ky',
  },
  {
    name: 'flag-kz',
  },
  {
    name: 'flag-la',
  },
  {
    name: 'flag-lb',
  },
  {
    name: 'flag-lc',
  },
  {
    name: 'flag-li',
  },
  {
    name: 'flag-lk',
  },
  {
    name: 'flag-lr',
  },
  {
    name: 'flag-ls',
  },
  {
    name: 'flag-lt',
  },
  {
    name: 'flag-lu',
  },
  {
    name: 'flag-lv',
  },
  {
    name: 'flag-ly',
  },
  {
    name: 'flag-ma',
  },
  {
    name: 'flag-mc',
  },
  {
    name: 'flag-md',
  },
  {
    name: 'flag-me',
  },
  {
    name: 'flag-mf',
  },
  {
    name: 'flag-mg',
  },
  {
    name: 'flag-mh',
  },
  {
    name: 'flag-mk',
  },
  {
    name: 'flag-ml',
  },
  {
    name: 'flag-mm',
  },
  {
    name: 'flag-mn',
  },
  {
    name: 'flag-mo',
  },
  {
    name: 'flag-mp',
  },
  {
    name: 'flag-mq',
  },
  {
    name: 'flag-mr',
  },
  {
    name: 'flag-ms',
  },
  {
    name: 'flag-mt',
  },
  {
    name: 'flag-mu',
  },
  {
    name: 'flag-mv',
  },
  {
    name: 'flag-mw',
  },
  {
    name: 'flag-mx',
  },
  {
    name: 'flag-my',
  },
  {
    name: 'flag-mz',
  },
  {
    name: 'flag-na',
  },
  {
    name: 'flag-nc',
  },
  {
    name: 'flag-ne',
  },
  {
    name: 'flag-nf',
  },
  {
    name: 'flag-ng',
  },
  {
    name: 'flag-ni',
  },
  {
    name: 'flag-nl',
  },
  {
    name: 'flag-no',
  },
  {
    name: 'flag-np',
  },
  {
    name: 'flag-nr',
  },
  {
    name: 'flag-nu',
  },
  {
    name: 'flag-nz',
  },
  {
    name: 'flag-om',
  },
  {
    name: 'flag-pa',
  },
  {
    name: 'flag-pe',
  },
  {
    name: 'flag-pf',
  },
  {
    name: 'flag-pg',
  },
  {
    name: 'flag-ph',
  },
  {
    name: 'flag-pk',
  },
  {
    name: 'flag-pl',
  },
  {
    name: 'flag-pm',
  },
  {
    name: 'flag-pn',
  },
  {
    name: 'flag-pr',
  },
  {
    name: 'flag-ps',
  },
  {
    name: 'flag-pt',
  },
  {
    name: 'flag-pw',
  },
  {
    name: 'flag-py',
  },
  {
    name: 'flag-qa',
  },
  {
    name: 'flag-re',
  },
  {
    name: 'flag-ro',
  },
  {
    name: 'flag-rs',
  },
  {
    name: 'ru',
  },
  {
    name: 'flag-ru',
  },
  {
    name: 'flag-rw',
  },
  {
    name: 'flag-sa',
  },
  {
    name: 'flag-sb',
  },
  {
    name: 'flag-sc',
  },
  {
    name: 'flag-sd',
  },
  {
    name: 'flag-se',
  },
  {
    name: 'flag-sg',
  },
  {
    name: 'flag-sh',
  },
  {
    name: 'flag-si',
  },
  {
    name: 'flag-sj',
  },
  {
    name: 'flag-sk',
  },
  {
    name: 'flag-sl',
  },
  {
    name: 'flag-sm',
  },
  {
    name: 'flag-sn',
  },
  {
    name: 'flag-so',
  },
  {
    name: 'flag-sr',
  },
  {
    name: 'flag-ss',
  },
  {
    name: 'flag-st',
  },
  {
    name: 'flag-sv',
  },
  {
    name: 'flag-sx',
  },
  {
    name: 'flag-sy',
  },
  {
    name: 'flag-sz',
  },
  {
    name: 'flag-ta',
  },
  {
    name: 'flag-tc',
  },
  {
    name: 'flag-td',
  },
  {
    name: 'flag-tf',
  },
  {
    name: 'flag-tg',
  },
  {
    name: 'flag-th',
  },
  {
    name: 'flag-tj',
  },
  {
    name: 'flag-tk',
  },
  {
    name: 'flag-tl',
  },
  {
    name: 'flag-tm',
  },
  {
    name: 'flag-tn',
  },
  {
    name: 'flag-to',
  },
  {
    name: 'flag-tr',
  },
  {
    name: 'flag-tt',
  },
  {
    name: 'flag-tv',
  },
  {
    name: 'flag-tw',
  },
  {
    name: 'flag-tz',
  },
  {
    name: 'flag-ua',
  },
  {
    name: 'flag-ug',
  },
  {
    name: 'flag-um',
  },
  {
    name: 'flag-un',
  },
  {
    name: 'us',
  },
  {
    name: 'flag-us',
  },
  {
    name: 'flag-uy',
  },
  {
    name: 'flag-uz',
  },
  {
    name: 'flag-va',
  },
  {
    name: 'flag-vc',
  },
  {
    name: 'flag-ve',
  },
  {
    name: 'flag-vg',
  },
  {
    name: 'flag-vi',
  },
  {
    name: 'flag-vn',
  },
  {
    name: 'flag-vu',
  },
  {
    name: 'flag-wf',
  },
  {
    name: 'flag-ws',
  },
  {
    name: 'flag-xk',
  },
  {
    name: 'flag-ye',
  },
  {
    name: 'flag-yt',
  },
  {
    name: 'flag-za',
  },
  {
    name: 'flag-zm',
  },
  {
    name: 'flag-zw',
  },
  {
    name: 'koko',
  },
  {
    name: 'sa',
  },
  {
    name: 'u7121',
  },
  {
    name: 'u6307',
  },
  {
    name: 'u7981',
  },
  {
    name: 'u7a7a',
  },
  {
    name: 'u5408',
  },
  {
    name: 'u6e80',
  },
  {
    name: 'u6709',
  },
  {
    name: 'u6708',
  },
  {
    name: 'u7533',
  },
  {
    name: 'u5272',
  },
  {
    name: 'u55b6',
  },
  {
    name: 'ideograph_advantage',
  },
  {
    name: 'accept',
  },
  {
    name: 'cyclone',
  },
  {
    name: 'foggy',
  },
  {
    name: 'closed_umbrella',
  },
  {
    name: 'night_with_stars',
  },
  {
    name: 'sunrise_over_mountains',
  },
  {
    name: 'sunrise',
  },
  {
    name: 'city_sunset',
  },
  {
    name: 'city_sunrise',
  },
  {
    name: 'rainbow',
  },
  {
    name: 'bridge_at_night',
  },
  {
    name: 'ocean',
  },
  {
    name: 'volcano',
  },
  {
    name: 'milky_way',
  },
  {
    name: 'earth_africa',
  },
  {
    name: 'earth_americas',
  },
  {
    name: 'earth_asia',
  },
  {
    name: 'globe_with_meridians',
  },
  {
    name: 'new_moon',
  },
  {
    name: 'waxing_crescent_moon',
  },
  {
    name: 'first_quarter_moon',
  },
  {
    name: 'moon',
  },
  {
    name: 'waxing_gibbous_moon',
  },
  {
    name: 'full_moon',
  },
  {
    name: 'waning_gibbous_moon',
  },
  {
    name: 'last_quarter_moon',
  },
  {
    name: 'waning_crescent_moon',
  },
  {
    name: 'crescent_moon',
  },
  {
    name: 'new_moon_with_face',
  },
  {
    name: 'first_quarter_moon_with_face',
  },
  {
    name: 'last_quarter_moon_with_face',
  },
  {
    name: 'full_moon_with_face',
  },
  {
    name: 'sun_with_face',
  },
  {
    name: 'star2',
  },
  {
    name: 'stars',
  },
  {
    name: 'thermometer',
  },
  {
    name: 'mostly_sunny',
  },
  {
    name: 'sun_small_cloud',
  },
  {
    name: 'barely_sunny',
  },
  {
    name: 'sun_behind_cloud',
  },
  {
    name: 'partly_sunny_rain',
  },
  {
    name: 'sun_behind_rain_cloud',
  },
  {
    name: 'rain_cloud',
  },
  {
    name: 'snow_cloud',
  },
  {
    name: 'lightning',
  },
  {
    name: 'lightning_cloud',
  },
  {
    name: 'tornado',
  },
  {
    name: 'tornado_cloud',
  },
  {
    name: 'fog',
  },
  {
    name: 'wind_blowing_face',
  },
  {
    name: 'hotdog',
  },
  {
    name: 'taco',
  },
  {
    name: 'burrito',
  },
  {
    name: 'chestnut',
  },
  {
    name: 'seedling',
  },
  {
    name: 'evergreen_tree',
  },
  {
    name: 'deciduous_tree',
  },
  {
    name: 'palm_tree',
  },
  {
    name: 'cactus',
  },
  {
    name: 'hot_pepper',
  },
  {
    name: 'tulip',
  },
  {
    name: 'cherry_blossom',
  },
  {
    name: 'rose',
  },
  {
    name: 'hibiscus',
  },
  {
    name: 'sunflower',
  },
  {
    name: 'blossom',
  },
  {
    name: 'corn',
  },
  {
    name: 'ear_of_rice',
  },
  {
    name: 'herb',
  },
  {
    name: 'four_leaf_clover',
  },
  {
    name: 'maple_leaf',
  },
  {
    name: 'fallen_leaf',
  },
  {
    name: 'leaves',
  },
  {
    name: 'mushroom',
  },
  {
    name: 'tomato',
  },
  {
    name: 'eggplant',
  },
  {
    name: 'grapes',
  },
  {
    name: 'melon',
  },
  {
    name: 'watermelon',
  },
  {
    name: 'tangerine',
  },
  {
    name: 'lemon',
  },
  {
    name: 'banana',
  },
  {
    name: 'pineapple',
  },
  {
    name: 'apple',
  },
  {
    name: 'green_apple',
  },
  {
    name: 'pear',
  },
  {
    name: 'peach',
  },
  {
    name: 'cherries',
  },
  {
    name: 'strawberry',
  },
  {
    name: 'hamburger',
  },
  {
    name: 'pizza',
  },
  {
    name: 'meat_on_bone',
  },
  {
    name: 'poultry_leg',
  },
  {
    name: 'rice_cracker',
  },
  {
    name: 'rice_ball',
  },
  {
    name: 'rice',
  },
  {
    name: 'curry',
  },
  {
    name: 'ramen',
  },
  {
    name: 'spaghetti',
  },
  {
    name: 'bread',
  },
  {
    name: 'fries',
  },
  {
    name: 'sweet_potato',
  },
  {
    name: 'dango',
  },
  {
    name: 'oden',
  },
  {
    name: 'sushi',
  },
  {
    name: 'fried_shrimp',
  },
  {
    name: 'fish_cake',
  },
  {
    name: 'icecream',
  },
  {
    name: 'shaved_ice',
  },
  {
    name: 'ice_cream',
  },
  {
    name: 'doughnut',
  },
  {
    name: 'cookie',
  },
  {
    name: 'chocolate_bar',
  },
  {
    name: 'candy',
  },
  {
    name: 'lollipop',
  },
  {
    name: 'custard',
  },
  {
    name: 'honey_pot',
  },
  {
    name: 'cake',
  },
  {
    name: 'bento',
  },
  {
    name: 'stew',
  },
  {
    name: 'fried_egg',
  },
  {
    name: 'cooking',
  },
  {
    name: 'fork_and_knife',
  },
  {
    name: 'tea',
  },
  {
    name: 'sake',
  },
  {
    name: 'wine_glass',
  },
  {
    name: 'cocktail',
  },
  {
    name: 'tropical_drink',
  },
  {
    name: 'beer',
  },
  {
    name: 'beers',
  },
  {
    name: 'baby_bottle',
  },
  {
    name: 'knife_fork_plate',
  },
  {
    name: 'champagne',
  },
  {
    name: 'popcorn',
  },
  {
    name: 'ribbon',
  },
  {
    name: 'gift',
  },
  {
    name: 'birthday',
  },
  {
    name: 'jack_o_lantern',
  },
  {
    name: 'christmas_tree',
  },
  {
    name: 'santa',
  },
  {
    name: 'fireworks',
  },
  {
    name: 'sparkler',
  },
  {
    name: 'balloon',
  },
  {
    name: 'tada',
  },
  {
    name: 'confetti_ball',
  },
  {
    name: 'tanabata_tree',
  },
  {
    name: 'crossed_flags',
  },
  {
    name: 'bamboo',
  },
  {
    name: 'dolls',
  },
  {
    name: 'flags',
  },
  {
    name: 'wind_chime',
  },
  {
    name: 'rice_scene',
  },
  {
    name: 'school_satchel',
  },
  {
    name: 'mortar_board',
  },
  {
    name: 'medal',
  },
  {
    name: 'reminder_ribbon',
  },
  {
    name: 'studio_microphone',
  },
  {
    name: 'level_slider',
  },
  {
    name: 'control_knobs',
  },
  {
    name: 'film_frames',
  },
  {
    name: 'admission_tickets',
  },
  {
    name: 'carousel_horse',
  },
  {
    name: 'ferris_wheel',
  },
  {
    name: 'roller_coaster',
  },
  {
    name: 'fishing_pole_and_fish',
  },
  {
    name: 'microphone',
  },
  {
    name: 'movie_camera',
  },
  {
    name: 'cinema',
  },
  {
    name: 'headphones',
  },
  {
    name: 'art',
  },
  {
    name: 'tophat',
  },
  {
    name: 'circus_tent',
  },
  {
    name: 'ticket',
  },
  {
    name: 'clapper',
  },
  {
    name: 'performing_arts',
  },
  {
    name: 'video_game',
  },
  {
    name: 'dart',
  },
  {
    name: 'slot_machine',
  },
  {
    name: '8ball',
  },
  {
    name: 'game_die',
  },
  {
    name: 'bowling',
  },
  {
    name: 'flower_playing_cards',
  },
  {
    name: 'musical_note',
  },
  {
    name: 'notes',
  },
  {
    name: 'saxophone',
  },
  {
    name: 'guitar',
  },
  {
    name: 'musical_keyboard',
  },
  {
    name: 'trumpet',
  },
  {
    name: 'violin',
  },
  {
    name: 'musical_score',
  },
  {
    name: 'running_shirt_with_sash',
  },
  {
    name: 'tennis',
  },
  {
    name: 'ski',
  },
  {
    name: 'basketball',
  },
  {
    name: 'checkered_flag',
  },
  {
    name: 'snowboarder',
  },
  {
    name: 'woman-running',
  },
  {
    name: 'man-running',
  },
  {
    name: 'runner',
  },
  {
    name: 'running',
  },
  {
    name: 'woman-surfing',
  },
  {
    name: 'man-surfing',
  },
  {
    name: 'surfer',
  },
  {
    name: 'sports_medal',
  },
  {
    name: 'trophy',
  },
  {
    name: 'horse_racing',
  },
  {
    name: 'football',
  },
  {
    name: 'rugby_football',
  },
  {
    name: 'woman-swimming',
  },
  {
    name: 'man-swimming',
  },
  {
    name: 'swimmer',
  },
  {
    name: 'woman-lifting-weights',
  },
  {
    name: 'man-lifting-weights',
  },
  {
    name: 'weight_lifter',
  },
  {
    name: 'woman-golfing',
  },
  {
    name: 'man-golfing',
  },
  {
    name: 'golfer',
  },
  {
    name: 'racing_motorcycle',
  },
  {
    name: 'racing_car',
  },
  {
    name: 'cricket_bat_and_ball',
  },
  {
    name: 'volleyball',
  },
  {
    name: 'field_hockey_stick_and_ball',
  },
  {
    name: 'ice_hockey_stick_and_puck',
  },
  {
    name: 'table_tennis_paddle_and_ball',
  },
  {
    name: 'snow_capped_mountain',
  },
  {
    name: 'camping',
  },
  {
    name: 'beach_with_umbrella',
  },
  {
    name: 'building_construction',
  },
  {
    name: 'house_buildings',
  },
  {
    name: 'cityscape',
  },
  {
    name: 'derelict_house_building',
  },
  {
    name: 'classical_building',
  },
  {
    name: 'desert',
  },
  {
    name: 'desert_island',
  },
  {
    name: 'national_park',
  },
  {
    name: 'stadium',
  },
  {
    name: 'house',
  },
  {
    name: 'house_with_garden',
  },
  {
    name: 'office',
  },
  {
    name: 'post_office',
  },
  {
    name: 'european_post_office',
  },
  {
    name: 'hospital',
  },
  {
    name: 'bank',
  },
  {
    name: 'atm',
  },
  {
    name: 'hotel',
  },
  {
    name: 'love_hotel',
  },
  {
    name: 'convenience_store',
  },
  {
    name: 'school',
  },
  {
    name: 'department_store',
  },
  {
    name: 'factory',
  },
  {
    name: 'izakaya_lantern',
  },
  {
    name: 'lantern',
  },
  {
    name: 'japanese_castle',
  },
  {
    name: 'european_castle',
  },
  {
    name: 'rainbow-flag',
  },
  {
    name: 'transgender_flag',
  },
  {
    name: 'waving_white_flag',
  },
  {
    name: 'pirate_flag',
  },
  {
    name: 'flag-england',
  },
  {
    name: 'flag-scotland',
  },
  {
    name: 'flag-wales',
  },
  {
    name: 'waving_black_flag',
  },
  {
    name: 'rosette',
  },
  {
    name: 'label',
  },
  {
    name: 'badminton_racquet_and_shuttlecock',
  },
  {
    name: 'bow_and_arrow',
  },
  {
    name: 'amphora',
  },
  {
    name: 'skin-tone-2',
  },
  {
    name: 'skin-tone-3',
  },
  {
    name: 'skin-tone-4',
  },
  {
    name: 'skin-tone-5',
  },
  {
    name: 'skin-tone-6',
  },
  {
    name: 'rat',
  },
  {
    name: 'mouse2',
  },
  {
    name: 'ox',
  },
  {
    name: 'water_buffalo',
  },
  {
    name: 'cow2',
  },
  {
    name: 'tiger2',
  },
  {
    name: 'leopard',
  },
  {
    name: 'rabbit2',
  },
  {
    name: 'black_cat',
  },
  {
    name: 'cat2',
  },
  {
    name: 'dragon',
  },
  {
    name: 'crocodile',
  },
  {
    name: 'whale2',
  },
  {
    name: 'snail',
  },
  {
    name: 'snake',
  },
  {
    name: 'racehorse',
  },
  {
    name: 'ram',
  },
  {
    name: 'goat',
  },
  {
    name: 'sheep',
  },
  {
    name: 'monkey',
  },
  {
    name: 'rooster',
  },
  {
    name: 'chicken',
  },
  {
    name: 'service_dog',
  },
  {
    name: 'dog2',
  },
  {
    name: 'pig2',
  },
  {
    name: 'boar',
  },
  {
    name: 'elephant',
  },
  {
    name: 'octopus',
  },
  {
    name: 'shell',
  },
  {
    name: 'bug',
  },
  {
    name: 'ant',
  },
  {
    name: 'bee',
  },
  {
    name: 'honeybee',
  },
  {
    name: 'ladybug',
  },
  {
    name: 'lady_beetle',
  },
  {
    name: 'fish',
  },
  {
    name: 'tropical_fish',
  },
  {
    name: 'blowfish',
  },
  {
    name: 'turtle',
  },
  {
    name: 'hatching_chick',
  },
  {
    name: 'baby_chick',
  },
  {
    name: 'hatched_chick',
  },
  {
    name: 'bird',
  },
  {
    name: 'penguin',
  },
  {
    name: 'koala',
  },
  {
    name: 'poodle',
  },
  {
    name: 'dromedary_camel',
  },
  {
    name: 'camel',
  },
  {
    name: 'dolphin',
  },
  {
    name: 'flipper',
  },
  {
    name: 'mouse',
  },
  {
    name: 'cow',
  },
  {
    name: 'tiger',
  },
  {
    name: 'rabbit',
  },
  {
    name: 'cat',
  },
  {
    name: 'dragon_face',
  },
  {
    name: 'whale',
  },
  {
    name: 'horse',
  },
  {
    name: 'monkey_face',
  },
  {
    name: 'dog',
  },
  {
    name: 'pig',
  },
  {
    name: 'frog',
  },
  {
    name: 'hamster',
  },
  {
    name: 'wolf',
  },
  {
    name: 'polar_bear',
  },
  {
    name: 'bear',
  },
  {
    name: 'panda_face',
  },
  {
    name: 'pig_nose',
  },
  {
    name: 'feet',
  },
  {
    name: 'paw_prints',
  },
  {
    name: 'chipmunk',
  },
  {
    name: 'eyes',
  },
  {
    name: 'eye-in-speech-bubble',
  },
  {
    name: 'eye',
  },
  {
    name: 'ear',
  },
  {
    name: 'nose',
  },
  {
    name: 'lips',
  },
  {
    name: 'tongue',
  },
  {
    name: 'point_up_2',
  },
  {
    name: 'point_down',
  },
  {
    name: 'point_left',
  },
  {
    name: 'point_right',
  },
  {
    name: 'facepunch',
  },
  {
    name: 'punch',
  },
  {
    name: 'wave',
  },
  {
    name: 'ok_hand',
  },
  {
    name: '+1',
  },
  {
    name: 'thumbsup',
  },
  {
    name: '-1',
  },
  {
    name: 'thumbsdown',
  },
  {
    name: 'clap',
  },
  {
    name: 'open_hands',
  },
  {
    name: 'crown',
  },
  {
    name: 'womans_hat',
  },
  {
    name: 'eyeglasses',
  },
  {
    name: 'necktie',
  },
  {
    name: 'shirt',
  },
  {
    name: 'tshirt',
  },
  {
    name: 'jeans',
  },
  {
    name: 'dress',
  },
  {
    name: 'kimono',
  },
  {
    name: 'bikini',
  },
  {
    name: 'womans_clothes',
  },
  {
    name: 'purse',
  },
  {
    name: 'handbag',
  },
  {
    name: 'pouch',
  },
  {
    name: 'mans_shoe',
  },
  {
    name: 'shoe',
  },
  {
    name: 'athletic_shoe',
  },
  {
    name: 'high_heel',
  },
  {
    name: 'sandal',
  },
  {
    name: 'boot',
  },
  {
    name: 'footprints',
  },
  {
    name: 'bust_in_silhouette',
  },
  {
    name: 'busts_in_silhouette',
  },
  {
    name: 'boy',
  },
  {
    name: 'girl',
  },
  {
    name: 'male-farmer',
  },
  {
    name: 'male-cook',
  },
  {
    name: 'man_feeding_baby',
  },
  {
    name: 'male-student',
  },
  {
    name: 'male-singer',
  },
  {
    name: 'male-artist',
  },
  {
    name: 'male-teacher',
  },
  {
    name: 'male-factory-worker',
  },
  {
    name: 'man-boy-boy',
  },
  {
    name: 'man-boy',
  },
  {
    name: 'man-girl-boy',
  },
  {
    name: 'man-girl-girl',
  },
  {
    name: 'man-girl',
  },
  {
    name: 'man-man-boy',
  },
  {
    name: 'man-man-boy-boy',
  },
  {
    name: 'man-man-girl',
  },
  {
    name: 'man-man-girl-boy',
  },
  {
    name: 'man-man-girl-girl',
  },
  {
    name: 'man-woman-boy',
  },
  {
    name: 'man-woman-boy-boy',
  },
  {
    name: 'man-woman-girl',
  },
  {
    name: 'man-woman-girl-boy',
  },
  {
    name: 'man-woman-girl-girl',
  },
  {
    name: 'male-technologist',
  },
  {
    name: 'male-office-worker',
  },
  {
    name: 'male-mechanic',
  },
  {
    name: 'male-scientist',
  },
  {
    name: 'male-astronaut',
  },
  {
    name: 'male-firefighter',
  },
  {
    name: 'man_with_probing_cane',
  },
  {
    name: 'red_haired_man',
  },
  {
    name: 'curly_haired_man',
  },
  {
    name: 'bald_man',
  },
  {
    name: 'white_haired_man',
  },
  {
    name: 'man_in_motorized_wheelchair',
  },
  {
    name: 'man_in_manual_wheelchair',
  },
  {
    name: 'male-doctor',
  },
  {
    name: 'male-judge',
  },
  {
    name: 'male-pilot',
  },
  {
    name: 'man-heart-man',
  },
  {
    name: 'man-kiss-man',
  },
  {
    name: 'man',
  },
  {
    name: 'female-farmer',
  },
  {
    name: 'female-cook',
  },
  {
    name: 'woman_feeding_baby',
  },
  {
    name: 'female-student',
  },
  {
    name: 'female-singer',
  },
  {
    name: 'female-artist',
  },
  {
    name: 'female-teacher',
  },
  {
    name: 'female-factory-worker',
  },
  {
    name: 'woman-boy-boy',
  },
  {
    name: 'woman-boy',
  },
  {
    name: 'woman-girl-boy',
  },
  {
    name: 'woman-girl-girl',
  },
  {
    name: 'woman-girl',
  },
  {
    name: 'woman-woman-boy',
  },
  {
    name: 'woman-woman-boy-boy',
  },
  {
    name: 'woman-woman-girl',
  },
  {
    name: 'woman-woman-girl-boy',
  },
  {
    name: 'woman-woman-girl-girl',
  },
  {
    name: 'female-technologist',
  },
  {
    name: 'female-office-worker',
  },
  {
    name: 'female-mechanic',
  },
  {
    name: 'female-scientist',
  },
  {
    name: 'female-astronaut',
  },
  {
    name: 'female-firefighter',
  },
  {
    name: 'woman_with_probing_cane',
  },
  {
    name: 'red_haired_woman',
  },
  {
    name: 'curly_haired_woman',
  },
  {
    name: 'bald_woman',
  },
  {
    name: 'white_haired_woman',
  },
  {
    name: 'woman_in_motorized_wheelchair',
  },
  {
    name: 'woman_in_manual_wheelchair',
  },
  {
    name: 'female-doctor',
  },
  {
    name: 'female-judge',
  },
  {
    name: 'female-pilot',
  },
  {
    name: 'woman-heart-man',
  },
  {
    name: 'woman-heart-woman',
  },
  {
    name: 'woman-kiss-man',
  },
  {
    name: 'woman-kiss-woman',
  },
  {
    name: 'woman',
  },
  {
    name: 'family',
  },
  {
    name: 'man_and_woman_holding_hands',
  },
  {
    name: 'woman_and_man_holding_hands',
  },
  {
    name: 'couple',
  },
  {
    name: 'two_men_holding_hands',
  },
  {
    name: 'men_holding_hands',
  },
  {
    name: 'two_women_holding_hands',
  },
  {
    name: 'women_holding_hands',
  },
  {
    name: 'female-police-officer',
  },
  {
    name: 'male-police-officer',
  },
  {
    name: 'cop',
  },
  {
    name: 'women-with-bunny-ears-partying',
  },
  {
    name: 'woman-with-bunny-ears-partying',
  },
  {
    name: 'men-with-bunny-ears-partying',
  },
  {
    name: 'man-with-bunny-ears-partying',
  },
  {
    name: 'dancers',
  },
  {
    name: 'woman_with_veil',
  },
  {
    name: 'man_with_veil',
  },
  {
    name: 'bride_with_veil',
  },
  {
    name: 'blond-haired-woman',
  },
  {
    name: 'blond-haired-man',
  },
  {
    name: 'person_with_blond_hair',
  },
  {
    name: 'man_with_gua_pi_mao',
  },
  {
    name: 'woman-wearing-turban',
  },
  {
    name: 'man-wearing-turban',
  },
  {
    name: 'man_with_turban',
  },
  {
    name: 'older_man',
  },
  {
    name: 'older_woman',
  },
  {
    name: 'baby',
  },
  {
    name: 'female-construction-worker',
  },
  {
    name: 'male-construction-worker',
  },
  {
    name: 'construction_worker',
  },
  {
    name: 'princess',
  },
  {
    name: 'japanese_ogre',
  },
  {
    name: 'japanese_goblin',
  },
  {
    name: 'ghost',
  },
  {
    name: 'angel',
  },
  {
    name: 'alien',
  },
  {
    name: 'space_invader',
  },
  {
    name: 'imp',
  },
  {
    name: 'skull',
  },
  {
    name: 'woman-tipping-hand',
  },
  {
    name: 'man-tipping-hand',
  },
  {
    name: 'information_desk_person',
  },
  {
    name: 'female-guard',
  },
  {
    name: 'male-guard',
  },
  {
    name: 'guardsman',
  },
  {
    name: 'dancer',
  },
  {
    name: 'lipstick',
  },
  {
    name: 'nail_care',
  },
  {
    name: 'woman-getting-massage',
  },
  {
    name: 'man-getting-massage',
  },
  {
    name: 'massage',
  },
  {
    name: 'woman-getting-haircut',
  },
  {
    name: 'man-getting-haircut',
  },
  {
    name: 'haircut',
  },
  {
    name: 'barber',
  },
  {
    name: 'syringe',
  },
  {
    name: 'pill',
  },
  {
    name: 'kiss',
  },
  {
    name: 'love_letter',
  },
  {
    name: 'ring',
  },
  {
    name: 'gem',
  },
  {
    name: 'couplekiss',
  },
  {
    name: 'bouquet',
  },
  {
    name: 'couple_with_heart',
  },
  {
    name: 'wedding',
  },
  {
    name: 'heartbeat',
  },
  {
    name: 'broken_heart',
  },
  {
    name: 'two_hearts',
  },
  {
    name: 'sparkling_heart',
  },
  {
    name: 'heartpulse',
  },
  {
    name: 'cupid',
  },
  {
    name: 'blue_heart',
  },
  {
    name: 'green_heart',
  },
  {
    name: 'yellow_heart',
  },
  {
    name: 'purple_heart',
  },
  {
    name: 'gift_heart',
  },
  {
    name: 'revolving_hearts',
  },
  {
    name: 'heart_decoration',
  },
  {
    name: 'diamond_shape_with_a_dot_inside',
  },
  {
    name: 'bulb',
  },
  {
    name: 'anger',
  },
  {
    name: 'bomb',
  },
  {
    name: 'zzz',
  },
  {
    name: 'boom',
  },
  {
    name: 'collision',
  },
  {
    name: 'sweat_drops',
  },
  {
    name: 'droplet',
  },
  {
    name: 'dash',
  },
  {
    name: 'hankey',
  },
  {
    name: 'poop',
  },
  {
    name: 'shit',
  },
  {
    name: 'muscle',
  },
  {
    name: 'dizzy',
  },
  {
    name: 'speech_balloon',
  },
  {
    name: 'thought_balloon',
  },
  {
    name: 'white_flower',
  },
  {
    name: '100',
  },
  {
    name: 'moneybag',
  },
  {
    name: 'currency_exchange',
  },
  {
    name: 'heavy_dollar_sign',
  },
  {
    name: 'credit_card',
  },
  {
    name: 'yen',
  },
  {
    name: 'dollar',
  },
  {
    name: 'euro',
  },
  {
    name: 'pound',
  },
  {
    name: 'money_with_wings',
  },
  {
    name: 'chart',
  },
  {
    name: 'seat',
  },
  {
    name: 'computer',
  },
  {
    name: 'briefcase',
  },
  {
    name: 'minidisc',
  },
  {
    name: 'floppy_disk',
  },
  {
    name: 'cd',
  },
  {
    name: 'dvd',
  },
  {
    name: 'file_folder',
  },
  {
    name: 'open_file_folder',
  },
  {
    name: 'page_with_curl',
  },
  {
    name: 'page_facing_up',
  },
  {
    name: 'date',
  },
  {
    name: 'calendar',
  },
  {
    name: 'card_index',
  },
  {
    name: 'chart_with_upwards_trend',
  },
  {
    name: 'chart_with_downwards_trend',
  },
  {
    name: 'bar_chart',
  },
  {
    name: 'clipboard',
  },
  {
    name: 'pushpin',
  },
  {
    name: 'round_pushpin',
  },
  {
    name: 'paperclip',
  },
  {
    name: 'straight_ruler',
  },
  {
    name: 'triangular_ruler',
  },
  {
    name: 'bookmark_tabs',
  },
  {
    name: 'ledger',
  },
  {
    name: 'notebook',
  },
  {
    name: 'notebook_with_decorative_cover',
  },
  {
    name: 'closed_book',
  },
  {
    name: 'book',
  },
  {
    name: 'open_book',
  },
  {
    name: 'green_book',
  },
  {
    name: 'blue_book',
  },
  {
    name: 'orange_book',
  },
  {
    name: 'books',
  },
  {
    name: 'name_badge',
  },
  {
    name: 'scroll',
  },
  {
    name: 'memo',
  },
  {
    name: 'pencil',
  },
  {
    name: 'telephone_receiver',
  },
  {
    name: 'pager',
  },
  {
    name: 'fax',
  },
  {
    name: 'satellite_antenna',
  },
  {
    name: 'loudspeaker',
  },
  {
    name: 'mega',
  },
  {
    name: 'outbox_tray',
  },
  {
    name: 'inbox_tray',
  },
  {
    name: 'package',
  },
  {
    name: 'e-mail',
  },
  {
    name: 'incoming_envelope',
  },
  {
    name: 'envelope_with_arrow',
  },
  {
    name: 'mailbox_closed',
  },
  {
    name: 'mailbox',
  },
  {
    name: 'mailbox_with_mail',
  },
  {
    name: 'mailbox_with_no_mail',
  },
  {
    name: 'postbox',
  },
  {
    name: 'postal_horn',
  },
  {
    name: 'newspaper',
  },
  {
    name: 'iphone',
  },
  {
    name: 'calling',
  },
  {
    name: 'vibration_mode',
  },
  {
    name: 'mobile_phone_off',
  },
  {
    name: 'no_mobile_phones',
  },
  {
    name: 'signal_strength',
  },
  {
    name: 'camera',
  },
  {
    name: 'camera_with_flash',
  },
  {
    name: 'video_camera',
  },
  {
    name: 'tv',
  },
  {
    name: 'radio',
  },
  {
    name: 'vhs',
  },
  {
    name: 'film_projector',
  },
  {
    name: 'prayer_beads',
  },
  {
    name: 'twisted_rightwards_arrows',
  },
  {
    name: 'repeat',
  },
  {
    name: 'repeat_one',
  },
  {
    name: 'arrows_clockwise',
  },
  {
    name: 'arrows_counterclockwise',
  },
  {
    name: 'low_brightness',
  },
  {
    name: 'high_brightness',
  },
  {
    name: 'mute',
  },
  {
    name: 'speaker',
  },
  {
    name: 'sound',
  },
  {
    name: 'loud_sound',
  },
  {
    name: 'battery',
  },
  {
    name: 'electric_plug',
  },
  {
    name: 'mag',
  },
  {
    name: 'mag_right',
  },
  {
    name: 'lock_with_ink_pen',
  },
  {
    name: 'closed_lock_with_key',
  },
  {
    name: 'key',
  },
  {
    name: 'lock',
  },
  {
    name: 'unlock',
  },
  {
    name: 'bell',
  },
  {
    name: 'no_bell',
  },
  {
    name: 'bookmark',
  },
  {
    name: 'link',
  },
  {
    name: 'radio_button',
  },
  {
    name: 'back',
  },
  {
    name: 'end',
  },
  {
    name: 'on',
  },
  {
    name: 'soon',
  },
  {
    name: 'top',
  },
  {
    name: 'underage',
  },
  {
    name: 'keycap_ten',
  },
  {
    name: 'capital_abcd',
  },
  {
    name: 'abcd',
  },
  {
    name: '1234',
  },
  {
    name: 'symbols',
  },
  {
    name: 'abc',
  },
  {
    name: 'fire',
  },
  {
    name: 'flashlight',
  },
  {
    name: 'wrench',
  },
  {
    name: 'hammer',
  },
  {
    name: 'nut_and_bolt',
  },
  {
    name: 'hocho',
  },
  {
    name: 'knife',
  },
  {
    name: 'gun',
  },
  {
    name: 'microscope',
  },
  {
    name: 'telescope',
  },
  {
    name: 'crystal_ball',
  },
  {
    name: 'six_pointed_star',
  },
  {
    name: 'beginner',
  },
  {
    name: 'trident',
  },
  {
    name: 'black_square_button',
  },
  {
    name: 'white_square_button',
  },
  {
    name: 'red_circle',
  },
  {
    name: 'large_blue_circle',
  },
  {
    name: 'large_orange_diamond',
  },
  {
    name: 'large_blue_diamond',
  },
  {
    name: 'small_orange_diamond',
  },
  {
    name: 'small_blue_diamond',
  },
  {
    name: 'small_red_triangle',
  },
  {
    name: 'small_red_triangle_down',
  },
  {
    name: 'arrow_up_small',
  },
  {
    name: 'arrow_down_small',
  },
  {
    name: 'om_symbol',
  },
  {
    name: 'dove_of_peace',
  },
  {
    name: 'kaaba',
  },
  {
    name: 'mosque',
  },
  {
    name: 'synagogue',
  },
  {
    name: 'menorah_with_nine_branches',
  },
  {
    name: 'clock1',
  },
  {
    name: 'clock2',
  },
  {
    name: 'clock3',
  },
  {
    name: 'clock4',
  },
  {
    name: 'clock5',
  },
  {
    name: 'clock6',
  },
  {
    name: 'clock7',
  },
  {
    name: 'clock8',
  },
  {
    name: 'clock9',
  },
  {
    name: 'clock10',
  },
  {
    name: 'clock11',
  },
  {
    name: 'clock12',
  },
  {
    name: 'clock130',
  },
  {
    name: 'clock230',
  },
  {
    name: 'clock330',
  },
  {
    name: 'clock430',
  },
  {
    name: 'clock530',
  },
  {
    name: 'clock630',
  },
  {
    name: 'clock730',
  },
  {
    name: 'clock830',
  },
  {
    name: 'clock930',
  },
  {
    name: 'clock1030',
  },
  {
    name: 'clock1130',
  },
  {
    name: 'clock1230',
  },
  {
    name: 'candle',
  },
  {
    name: 'mantelpiece_clock',
  },
  {
    name: 'hole',
  },
  {
    name: 'man_in_business_suit_levitating',
  },
  {
    name: 'female-detective',
  },
  {
    name: 'male-detective',
  },
  {
    name: 'sleuth_or_spy',
  },
  {
    name: 'dark_sunglasses',
  },
  {
    name: 'spider',
  },
  {
    name: 'spider_web',
  },
  {
    name: 'joystick',
  },
  {
    name: 'man_dancing',
  },
  {
    name: 'linked_paperclips',
  },
  {
    name: 'lower_left_ballpoint_pen',
  },
  {
    name: 'lower_left_fountain_pen',
  },
  {
    name: 'lower_left_paintbrush',
  },
  {
    name: 'lower_left_crayon',
  },
  {
    name: 'raised_hand_with_fingers_splayed',
  },
  {
    name: 'middle_finger',
  },
  {
    name: 'reversed_hand_with_middle_finger_extended',
  },
  {
    name: 'spock-hand',
  },
  {
    name: 'black_heart',
  },
  {
    name: 'desktop_computer',
  },
  {
    name: 'printer',
  },
  {
    name: 'three_button_mouse',
  },
  {
    name: 'trackball',
  },
  {
    name: 'frame_with_picture',
  },
  {
    name: 'card_index_dividers',
  },
  {
    name: 'card_file_box',
  },
  {
    name: 'file_cabinet',
  },
  {
    name: 'wastebasket',
  },
  {
    name: 'spiral_note_pad',
  },
  {
    name: 'spiral_calendar_pad',
  },
  {
    name: 'compression',
  },
  {
    name: 'old_key',
  },
  {
    name: 'rolled_up_newspaper',
  },
  {
    name: 'dagger_knife',
  },
  {
    name: 'speaking_head_in_silhouette',
  },
  {
    name: 'left_speech_bubble',
  },
  {
    name: 'right_anger_bubble',
  },
  {
    name: 'ballot_box_with_ballot',
  },
  {
    name: 'world_map',
  },
  {
    name: 'mount_fuji',
  },
  {
    name: 'tokyo_tower',
  },
  {
    name: 'statue_of_liberty',
  },
  {
    name: 'japan',
  },
  {
    name: 'moyai',
  },
  {
    name: 'grinning',
  },
  {
    name: 'grin',
  },
  {
    name: 'joy',
  },
  {
    name: 'smiley',
  },
  {
    name: 'smile',
  },
  {
    name: 'sweat_smile',
  },
  {
    name: 'laughing',
  },
  {
    name: 'satisfied',
  },
  {
    name: 'innocent',
  },
  {
    name: 'smiling_imp',
  },
  {
    name: 'wink',
  },
  {
    name: 'blush',
  },
  {
    name: 'yum',
  },
  {
    name: 'relieved',
  },
  {
    name: 'heart_eyes',
  },
  {
    name: 'sunglasses',
  },
  {
    name: 'smirk',
  },
  {
    name: 'neutral_face',
  },
  {
    name: 'expressionless',
  },
  {
    name: 'unamused',
  },
  {
    name: 'sweat',
  },
  {
    name: 'pensive',
  },
  {
    name: 'confused',
  },
  {
    name: 'confounded',
  },
  {
    name: 'kissing',
  },
  {
    name: 'kissing_heart',
  },
  {
    name: 'kissing_smiling_eyes',
  },
  {
    name: 'kissing_closed_eyes',
  },
  {
    name: 'stuck_out_tongue',
  },
  {
    name: 'stuck_out_tongue_winking_eye',
  },
  {
    name: 'stuck_out_tongue_closed_eyes',
  },
  {
    name: 'disappointed',
  },
  {
    name: 'worried',
  },
  {
    name: 'angry',
  },
  {
    name: 'rage',
  },
  {
    name: 'cry',
  },
  {
    name: 'persevere',
  },
  {
    name: 'triumph',
  },
  {
    name: 'disappointed_relieved',
  },
  {
    name: 'frowning',
  },
  {
    name: 'anguished',
  },
  {
    name: 'fearful',
  },
  {
    name: 'weary',
  },
  {
    name: 'sleepy',
  },
  {
    name: 'tired_face',
  },
  {
    name: 'grimacing',
  },
  {
    name: 'sob',
  },
  {
    name: 'face_exhaling',
  },
  {
    name: 'open_mouth',
  },
  {
    name: 'hushed',
  },
  {
    name: 'cold_sweat',
  },
  {
    name: 'scream',
  },
  {
    name: 'astonished',
  },
  {
    name: 'flushed',
  },
  {
    name: 'sleeping',
  },
  {
    name: 'face_with_spiral_eyes',
  },
  {
    name: 'dizzy_face',
  },
  {
    name: 'face_in_clouds',
  },
  {
    name: 'no_mouth',
  },
  {
    name: 'mask',
  },
  {
    name: 'smile_cat',
  },
  {
    name: 'joy_cat',
  },
  {
    name: 'smiley_cat',
  },
  {
    name: 'heart_eyes_cat',
  },
  {
    name: 'smirk_cat',
  },
  {
    name: 'kissing_cat',
  },
  {
    name: 'pouting_cat',
  },
  {
    name: 'crying_cat_face',
  },
  {
    name: 'scream_cat',
  },
  {
    name: 'slightly_frowning_face',
  },
  {
    name: 'slightly_smiling_face',
  },
  {
    name: 'upside_down_face',
  },
  {
    name: 'face_with_rolling_eyes',
  },
  {
    name: 'woman-gesturing-no',
  },
  {
    name: 'man-gesturing-no',
  },
  {
    name: 'no_good',
  },
  {
    name: 'woman-gesturing-ok',
  },
  {
    name: 'man-gesturing-ok',
  },
  {
    name: 'ok_woman',
  },
  {
    name: 'woman-bowing',
  },
  {
    name: 'man-bowing',
  },
  {
    name: 'bow',
  },
  {
    name: 'see_no_evil',
  },
  {
    name: 'hear_no_evil',
  },
  {
    name: 'speak_no_evil',
  },
  {
    name: 'woman-raising-hand',
  },
  {
    name: 'man-raising-hand',
  },
  {
    name: 'raising_hand',
  },
  {
    name: 'raised_hands',
  },
  {
    name: 'woman-frowning',
  },
  {
    name: 'man-frowning',
  },
  {
    name: 'person_frowning',
  },
  {
    name: 'woman-pouting',
  },
  {
    name: 'man-pouting',
  },
  {
    name: 'person_with_pouting_face',
  },
  {
    name: 'pray',
  },
  {
    name: 'rocket',
  },
  {
    name: 'helicopter',
  },
  {
    name: 'steam_locomotive',
  },
  {
    name: 'railway_car',
  },
  {
    name: 'bullettrain_side',
  },
  {
    name: 'bullettrain_front',
  },
  {
    name: 'train2',
  },
  {
    name: 'metro',
  },
  {
    name: 'light_rail',
  },
  {
    name: 'station',
  },
  {
    name: 'tram',
  },
  {
    name: 'train',
  },
  {
    name: 'bus',
  },
  {
    name: 'oncoming_bus',
  },
  {
    name: 'trolleybus',
  },
  {
    name: 'busstop',
  },
  {
    name: 'minibus',
  },
  {
    name: 'ambulance',
  },
  {
    name: 'fire_engine',
  },
  {
    name: 'police_car',
  },
  {
    name: 'oncoming_police_car',
  },
  {
    name: 'taxi',
  },
  {
    name: 'oncoming_taxi',
  },
  {
    name: 'car',
  },
  {
    name: 'red_car',
  },
  {
    name: 'oncoming_automobile',
  },
  {
    name: 'blue_car',
  },
  {
    name: 'truck',
  },
  {
    name: 'articulated_lorry',
  },
  {
    name: 'tractor',
  },
  {
    name: 'monorail',
  },
  {
    name: 'mountain_railway',
  },
  {
    name: 'suspension_railway',
  },
  {
    name: 'mountain_cableway',
  },
  {
    name: 'aerial_tramway',
  },
  {
    name: 'ship',
  },
  {
    name: 'woman-rowing-boat',
  },
  {
    name: 'man-rowing-boat',
  },
  {
    name: 'rowboat',
  },
  {
    name: 'speedboat',
  },
  {
    name: 'traffic_light',
  },
  {
    name: 'vertical_traffic_light',
  },
  {
    name: 'construction',
  },
  {
    name: 'rotating_light',
  },
  {
    name: 'triangular_flag_on_post',
  },
  {
    name: 'door',
  },
  {
    name: 'no_entry_sign',
  },
  {
    name: 'smoking',
  },
  {
    name: 'no_smoking',
  },
  {
    name: 'put_litter_in_its_place',
  },
  {
    name: 'do_not_litter',
  },
  {
    name: 'potable_water',
  },
  {
    name: 'non-potable_water',
  },
  {
    name: 'bike',
  },
  {
    name: 'no_bicycles',
  },
  {
    name: 'woman-biking',
  },
  {
    name: 'man-biking',
  },
  {
    name: 'bicyclist',
  },
  {
    name: 'woman-mountain-biking',
  },
  {
    name: 'man-mountain-biking',
  },
  {
    name: 'mountain_bicyclist',
  },
  {
    name: 'woman-walking',
  },
  {
    name: 'man-walking',
  },
  {
    name: 'walking',
  },
  {
    name: 'no_pedestrians',
  },
  {
    name: 'children_crossing',
  },
  {
    name: 'mens',
  },
  {
    name: 'womens',
  },
  {
    name: 'restroom',
  },
  {
    name: 'baby_symbol',
  },
  {
    name: 'toilet',
  },
  {
    name: 'wc',
  },
  {
    name: 'shower',
  },
  {
    name: 'bath',
  },
  {
    name: 'bathtub',
  },
  {
    name: 'passport_control',
  },
  {
    name: 'customs',
  },
  {
    name: 'baggage_claim',
  },
  {
    name: 'left_luggage',
  },
  {
    name: 'couch_and_lamp',
  },
  {
    name: 'sleeping_accommodation',
  },
  {
    name: 'shopping_bags',
  },
  {
    name: 'bellhop_bell',
  },
  {
    name: 'bed',
  },
  {
    name: 'place_of_worship',
  },
  {
    name: 'octagonal_sign',
  },
  {
    name: 'shopping_trolley',
  },
  {
    name: 'hindu_temple',
  },
  {
    name: 'hut',
  },
  {
    name: 'elevator',
  },
  {
    name: 'hammer_and_wrench',
  },
  {
    name: 'shield',
  },
  {
    name: 'oil_drum',
  },
  {
    name: 'motorway',
  },
  {
    name: 'railway_track',
  },
  {
    name: 'motor_boat',
  },
  {
    name: 'small_airplane',
  },
  {
    name: 'airplane_departure',
  },
  {
    name: 'airplane_arriving',
  },
  {
    name: 'satellite',
  },
  {
    name: 'passenger_ship',
  },
  {
    name: 'scooter',
  },
  {
    name: 'motor_scooter',
  },
  {
    name: 'canoe',
  },
  {
    name: 'sled',
  },
  {
    name: 'flying_saucer',
  },
  {
    name: 'skateboard',
  },
  {
    name: 'auto_rickshaw',
  },
  {
    name: 'pickup_truck',
  },
  {
    name: 'roller_skate',
  },
  {
    name: 'large_orange_circle',
  },
  {
    name: 'large_yellow_circle',
  },
  {
    name: 'large_green_circle',
  },
  {
    name: 'large_purple_circle',
  },
  {
    name: 'large_brown_circle',
  },
  {
    name: 'large_red_square',
  },
  {
    name: 'large_blue_square',
  },
  {
    name: 'large_orange_square',
  },
  {
    name: 'large_yellow_square',
  },
  {
    name: 'large_green_square',
  },
  {
    name: 'large_purple_square',
  },
  {
    name: 'large_brown_square',
  },
  {
    name: 'pinched_fingers',
  },
  {
    name: 'white_heart',
  },
  {
    name: 'brown_heart',
  },
  {
    name: 'pinching_hand',
  },
  {
    name: 'zipper_mouth_face',
  },
  {
    name: 'money_mouth_face',
  },
  {
    name: 'face_with_thermometer',
  },
  {
    name: 'nerd_face',
  },
  {
    name: 'thinking_face',
  },
  {
    name: 'face_with_head_bandage',
  },
  {
    name: 'robot_face',
  },
  {
    name: 'hugging_face',
  },
  {
    name: 'the_horns',
  },
  {
    name: 'sign_of_the_horns',
  },
  {
    name: 'call_me_hand',
  },
  {
    name: 'raised_back_of_hand',
  },
  {
    name: 'left-facing_fist',
  },
  {
    name: 'right-facing_fist',
  },
  {
    name: 'handshake',
  },
  {
    name: 'crossed_fingers',
  },
  {
    name: 'hand_with_index_and_middle_fingers_crossed',
  },
  {
    name: 'i_love_you_hand_sign',
  },
  {
    name: 'face_with_cowboy_hat',
  },
  {
    name: 'clown_face',
  },
  {
    name: 'nauseated_face',
  },
  {
    name: 'rolling_on_the_floor_laughing',
  },
  {
    name: 'drooling_face',
  },
  {
    name: 'lying_face',
  },
  {
    name: 'woman-facepalming',
  },
  {
    name: 'man-facepalming',
  },
  {
    name: 'face_palm',
  },
  {
    name: 'sneezing_face',
  },
  {
    name: 'face_with_raised_eyebrow',
  },
  {
    name: 'face_with_one_eyebrow_raised',
  },
  {
    name: 'star-struck',
  },
  {
    name: 'grinning_face_with_star_eyes',
  },
  {
    name: 'zany_face',
  },
  {
    name: 'grinning_face_with_one_large_and_one_small_eye',
  },
  {
    name: 'shushing_face',
  },
  {
    name: 'face_with_finger_covering_closed_lips',
  },
  {
    name: 'face_with_symbols_on_mouth',
  },
  {
    name: 'serious_face_with_symbols_covering_mouth',
  },
  {
    name: 'face_with_hand_over_mouth',
  },
  {
    name: 'smiling_face_with_smiling_eyes_and_hand_covering_mouth',
  },
  {
    name: 'face_vomiting',
  },
  {
    name: 'face_with_open_mouth_vomiting',
  },
  {
    name: 'exploding_head',
  },
  {
    name: 'shocked_face_with_exploding_head',
  },
  {
    name: 'pregnant_woman',
  },
  {
    name: 'breast-feeding',
  },
  {
    name: 'palms_up_together',
  },
  {
    name: 'selfie',
  },
  {
    name: 'prince',
  },
  {
    name: 'woman_in_tuxedo',
  },
  {
    name: 'man_in_tuxedo',
  },
  {
    name: 'person_in_tuxedo',
  },
  {
    name: 'mrs_claus',
  },
  {
    name: 'mother_christmas',
  },
  {
    name: 'woman-shrugging',
  },
  {
    name: 'man-shrugging',
  },
  {
    name: 'shrug',
  },
  {
    name: 'woman-cartwheeling',
  },
  {
    name: 'man-cartwheeling',
  },
  {
    name: 'person_doing_cartwheel',
  },
  {
    name: 'woman-juggling',
  },
  {
    name: 'man-juggling',
  },
  {
    name: 'juggling',
  },
  {
    name: 'fencer',
  },
  {
    name: 'woman-wrestling',
  },
  {
    name: 'man-wrestling',
  },
  {
    name: 'wrestlers',
  },
  {
    name: 'woman-playing-water-polo',
  },
  {
    name: 'man-playing-water-polo',
  },
  {
    name: 'water_polo',
  },
  {
    name: 'woman-playing-handball',
  },
  {
    name: 'man-playing-handball',
  },
  {
    name: 'handball',
  },
  {
    name: 'diving_mask',
  },
  {
    name: 'wilted_flower',
  },
  {
    name: 'drum_with_drumsticks',
  },
  {
    name: 'clinking_glasses',
  },
  {
    name: 'tumbler_glass',
  },
  {
    name: 'spoon',
  },
  {
    name: 'goal_net',
  },
  {
    name: 'first_place_medal',
  },
  {
    name: 'second_place_medal',
  },
  {
    name: 'third_place_medal',
  },
  {
    name: 'boxing_glove',
  },
  {
    name: 'martial_arts_uniform',
  },
  {
    name: 'curling_stone',
  },
  {
    name: 'lacrosse',
  },
  {
    name: 'softball',
  },
  {
    name: 'flying_disc',
  },
  {
    name: 'croissant',
  },
  {
    name: 'avocado',
  },
  {
    name: 'cucumber',
  },
  {
    name: 'bacon',
  },
  {
    name: 'potato',
  },
  {
    name: 'carrot',
  },
  {
    name: 'baguette_bread',
  },
  {
    name: 'green_salad',
  },
  {
    name: 'shallow_pan_of_food',
  },
  {
    name: 'stuffed_flatbread',
  },
  {
    name: 'egg',
  },
  {
    name: 'glass_of_milk',
  },
  {
    name: 'peanuts',
  },
  {
    name: 'kiwifruit',
  },
  {
    name: 'pancakes',
  },
  {
    name: 'dumpling',
  },
  {
    name: 'fortune_cookie',
  },
  {
    name: 'takeout_box',
  },
  {
    name: 'chopsticks',
  },
  {
    name: 'bowl_with_spoon',
  },
  {
    name: 'cup_with_straw',
  },
  {
    name: 'coconut',
  },
  {
    name: 'broccoli',
  },
  {
    name: 'pie',
  },
  {
    name: 'pretzel',
  },
  {
    name: 'cut_of_meat',
  },
  {
    name: 'sandwich',
  },
  {
    name: 'canned_food',
  },
  {
    name: 'leafy_green',
  },
  {
    name: 'mango',
  },
  {
    name: 'moon_cake',
  },
  {
    name: 'bagel',
  },
  {
    name: 'smiling_face_with_3_hearts',
  },
  {
    name: 'yawning_face',
  },
  {
    name: 'smiling_face_with_tear',
  },
  {
    name: 'partying_face',
  },
  {
    name: 'woozy_face',
  },
  {
    name: 'hot_face',
  },
  {
    name: 'cold_face',
  },
  {
    name: 'ninja',
  },
  {
    name: 'disguised_face',
  },
  {
    name: 'pleading_face',
  },
  {
    name: 'sari',
  },
  {
    name: 'lab_coat',
  },
  {
    name: 'goggles',
  },
  {
    name: 'hiking_boot',
  },
  {
    name: 'womans_flat_shoe',
  },
  {
    name: 'crab',
  },
  {
    name: 'lion_face',
  },
  {
    name: 'scorpion',
  },
  {
    name: 'turkey',
  },
  {
    name: 'unicorn_face',
  },
  {
    name: 'eagle',
  },
  {
    name: 'duck',
  },
  {
    name: 'bat',
  },
  {
    name: 'shark',
  },
  {
    name: 'owl',
  },
  {
    name: 'fox_face',
  },
  {
    name: 'butterfly',
  },
  {
    name: 'deer',
  },
  {
    name: 'gorilla',
  },
  {
    name: 'lizard',
  },
  {
    name: 'rhinoceros',
  },
  {
    name: 'shrimp',
  },
  {
    name: 'squid',
  },
  {
    name: 'giraffe_face',
  },
  {
    name: 'zebra_face',
  },
  {
    name: 'hedgehog',
  },
  {
    name: 'sauropod',
  },
  {
    name: 't-rex',
  },
  {
    name: 'cricket',
  },
  {
    name: 'kangaroo',
  },
  {
    name: 'llama',
  },
  {
    name: 'peacock',
  },
  {
    name: 'hippopotamus',
  },
  {
    name: 'parrot',
  },
  {
    name: 'raccoon',
  },
  {
    name: 'lobster',
  },
  {
    name: 'mosquito',
  },
  {
    name: 'microbe',
  },
  {
    name: 'badger',
  },
  {
    name: 'swan',
  },
  {
    name: 'mammoth',
  },
  {
    name: 'dodo',
  },
  {
    name: 'sloth',
  },
  {
    name: 'otter',
  },
  {
    name: 'orangutan',
  },
  {
    name: 'skunk',
  },
  {
    name: 'flamingo',
  },
  {
    name: 'oyster',
  },
  {
    name: 'beaver',
  },
  {
    name: 'bison',
  },
  {
    name: 'seal',
  },
  {
    name: 'guide_dog',
  },
  {
    name: 'probing_cane',
  },
  {
    name: 'bone',
  },
  {
    name: 'leg',
  },
  {
    name: 'foot',
  },
  {
    name: 'tooth',
  },
  {
    name: 'female_superhero',
  },
  {
    name: 'male_superhero',
  },
  {
    name: 'superhero',
  },
  {
    name: 'female_supervillain',
  },
  {
    name: 'male_supervillain',
  },
  {
    name: 'supervillain',
  },
  {
    name: 'safety_vest',
  },
  {
    name: 'ear_with_hearing_aid',
  },
  {
    name: 'motorized_wheelchair',
  },
  {
    name: 'manual_wheelchair',
  },
  {
    name: 'mechanical_arm',
  },
  {
    name: 'mechanical_leg',
  },
  {
    name: 'cheese_wedge',
  },
  {
    name: 'cupcake',
  },
  {
    name: 'salt',
  },
  {
    name: 'beverage_box',
  },
  {
    name: 'garlic',
  },
  {
    name: 'onion',
  },
  {
    name: 'falafel',
  },
  {
    name: 'waffle',
  },
  {
    name: 'butter',
  },
  {
    name: 'mate_drink',
  },
  {
    name: 'ice_cube',
  },
  {
    name: 'bubble_tea',
  },
  {
    name: 'woman_standing',
  },
  {
    name: 'man_standing',
  },
  {
    name: 'standing_person',
  },
  {
    name: 'woman_kneeling',
  },
  {
    name: 'man_kneeling',
  },
  {
    name: 'kneeling_person',
  },
  {
    name: 'deaf_woman',
  },
  {
    name: 'deaf_man',
  },
  {
    name: 'deaf_person',
  },
  {
    name: 'face_with_monocle',
  },
  {
    name: 'farmer',
  },
  {
    name: 'cook',
  },
  {
    name: 'person_feeding_baby',
  },
  {
    name: 'mx_claus',
  },
  {
    name: 'student',
  },
  {
    name: 'singer',
  },
  {
    name: 'artist',
  },
  {
    name: 'teacher',
  },
  {
    name: 'factory_worker',
  },
  {
    name: 'technologist',
  },
  {
    name: 'office_worker',
  },
  {
    name: 'mechanic',
  },
  {
    name: 'scientist',
  },
  {
    name: 'astronaut',
  },
  {
    name: 'firefighter',
  },
  {
    name: 'people_holding_hands',
  },
  {
    name: 'person_with_probing_cane',
  },
  {
    name: 'red_haired_person',
  },
  {
    name: 'curly_haired_person',
  },
  {
    name: 'bald_person',
  },
  {
    name: 'white_haired_person',
  },
  {
    name: 'person_in_motorized_wheelchair',
  },
  {
    name: 'person_in_manual_wheelchair',
  },
  {
    name: 'health_worker',
  },
  {
    name: 'judge',
  },
  {
    name: 'pilot',
  },
  {
    name: 'adult',
  },
  {
    name: 'child',
  },
  {
    name: 'older_adult',
  },
  {
    name: 'woman_with_beard',
  },
  {
    name: 'man_with_beard',
  },
  {
    name: 'bearded_person',
  },
  {
    name: 'person_with_headscarf',
  },
  {
    name: 'woman_in_steamy_room',
  },
  {
    name: 'man_in_steamy_room',
  },
  {
    name: 'person_in_steamy_room',
  },
  {
    name: 'woman_climbing',
  },
  {
    name: 'man_climbing',
  },
  {
    name: 'person_climbing',
  },
  {
    name: 'woman_in_lotus_position',
  },
  {
    name: 'man_in_lotus_position',
  },
  {
    name: 'person_in_lotus_position',
  },
  {
    name: 'female_mage',
  },
  {
    name: 'male_mage',
  },
  {
    name: 'mage',
  },
  {
    name: 'female_fairy',
  },
  {
    name: 'male_fairy',
  },
  {
    name: 'fairy',
  },
  {
    name: 'female_vampire',
  },
  {
    name: 'male_vampire',
  },
  {
    name: 'vampire',
  },
  {
    name: 'mermaid',
  },
  {
    name: 'merman',
  },
  {
    name: 'merperson',
  },
  {
    name: 'female_elf',
  },
  {
    name: 'male_elf',
  },
  {
    name: 'elf',
  },
  {
    name: 'female_genie',
  },
  {
    name: 'male_genie',
  },
  {
    name: 'genie',
  },
  {
    name: 'female_zombie',
  },
  {
    name: 'male_zombie',
  },
  {
    name: 'zombie',
  },
  {
    name: 'brain',
  },
  {
    name: 'orange_heart',
  },
  {
    name: 'billed_cap',
  },
  {
    name: 'scarf',
  },
  {
    name: 'gloves',
  },
  {
    name: 'coat',
  },
  {
    name: 'socks',
  },
  {
    name: 'red_envelope',
  },
  {
    name: 'firecracker',
  },
  {
    name: 'jigsaw',
  },
  {
    name: 'test_tube',
  },
  {
    name: 'petri_dish',
  },
  {
    name: 'dna',
  },
  {
    name: 'compass',
  },
  {
    name: 'abacus',
  },
  {
    name: 'fire_extinguisher',
  },
  {
    name: 'toolbox',
  },
  {
    name: 'bricks',
  },
  {
    name: 'magnet',
  },
  {
    name: 'luggage',
  },
  {
    name: 'lotion_bottle',
  },
  {
    name: 'thread',
  },
  {
    name: 'yarn',
  },
  {
    name: 'safety_pin',
  },
  {
    name: 'teddy_bear',
  },
  {
    name: 'broom',
  },
  {
    name: 'basket',
  },
  {
    name: 'roll_of_paper',
  },
  {
    name: 'soap',
  },
  {
    name: 'sponge',
  },
  {
    name: 'receipt',
  },
  {
    name: 'nazar_amulet',
  },
  {
    name: 'ballet_shoes',
  },
  {
    name: 'one-piece_swimsuit',
  },
  {
    name: 'briefs',
  },
  {
    name: 'shorts',
  },
  {
    name: 'thong_sandal',
  },
  {
    name: 'drop_of_blood',
  },
  {
    name: 'adhesive_bandage',
  },
  {
    name: 'stethoscope',
  },
  {
    name: 'yo-yo',
  },
  {
    name: 'kite',
  },
  {
    name: 'parachute',
  },
  {
    name: 'boomerang',
  },
  {
    name: 'magic_wand',
  },
  {
    name: 'pinata',
  },
  {
    name: 'nesting_dolls',
  },
  {
    name: 'ringed_planet',
  },
  {
    name: 'chair',
  },
  {
    name: 'razor',
  },
  {
    name: 'axe',
  },
  {
    name: 'diya_lamp',
  },
  {
    name: 'banjo',
  },
  {
    name: 'military_helmet',
  },
  {
    name: 'accordion',
  },
  {
    name: 'long_drum',
  },
  {
    name: 'coin',
  },
  {
    name: 'carpentry_saw',
  },
  {
    name: 'screwdriver',
  },
  {
    name: 'ladder',
  },
  {
    name: 'hook',
  },
  {
    name: 'mirror',
  },
  {
    name: 'window',
  },
  {
    name: 'plunger',
  },
  {
    name: 'sewing_needle',
  },
  {
    name: 'knot',
  },
  {
    name: 'bucket',
  },
  {
    name: 'mouse_trap',
  },
  {
    name: 'toothbrush',
  },
  {
    name: 'headstone',
  },
  {
    name: 'placard',
  },
  {
    name: 'rock',
  },
  {
    name: 'fly',
  },
  {
    name: 'worm',
  },
  {
    name: 'beetle',
  },
  {
    name: 'cockroach',
  },
  {
    name: 'potted_plant',
  },
  {
    name: 'wood',
  },
  {
    name: 'feather',
  },
  {
    name: 'anatomical_heart',
  },
  {
    name: 'lungs',
  },
  {
    name: 'people_hugging',
  },
  {
    name: 'blueberries',
  },
  {
    name: 'bell_pepper',
  },
  {
    name: 'olive',
  },
  {
    name: 'flatbread',
  },
  {
    name: 'tamale',
  },
  {
    name: 'fondue',
  },
  {
    name: 'teapot',
  },
  {
    name: 'bangbang',
  },
  {
    name: 'interrobang',
  },
  {
    name: 'tm',
  },
  {
    name: 'information_source',
  },
  {
    name: 'left_right_arrow',
  },
  {
    name: 'arrow_up_down',
  },
  {
    name: 'arrow_upper_left',
  },
  {
    name: 'arrow_upper_right',
  },
  {
    name: 'arrow_lower_right',
  },
  {
    name: 'arrow_lower_left',
  },
  {
    name: 'leftwards_arrow_with_hook',
  },
  {
    name: 'arrow_right_hook',
  },
  {
    name: 'watch',
  },
  {
    name: 'hourglass',
  },
  {
    name: 'keyboard',
  },
  {
    name: 'eject',
  },
  {
    name: 'fast_forward',
  },
  {
    name: 'rewind',
  },
  {
    name: 'arrow_double_up',
  },
  {
    name: 'arrow_double_down',
  },
  {
    name: 'black_right_pointing_double_triangle_with_vertical_bar',
  },
  {
    name: 'black_left_pointing_double_triangle_with_vertical_bar',
  },
  {
    name: 'black_right_pointing_triangle_with_double_vertical_bar',
  },
  {
    name: 'alarm_clock',
  },
  {
    name: 'stopwatch',
  },
  {
    name: 'timer_clock',
  },
  {
    name: 'hourglass_flowing_sand',
  },
  {
    name: 'double_vertical_bar',
  },
  {
    name: 'black_square_for_stop',
  },
  {
    name: 'black_circle_for_record',
  },
  {
    name: 'm',
  },
  {
    name: 'black_small_square',
  },
  {
    name: 'white_small_square',
  },
  {
    name: 'arrow_forward',
  },
  {
    name: 'arrow_backward',
  },
  {
    name: 'white_medium_square',
  },
  {
    name: 'black_medium_square',
  },
  {
    name: 'white_medium_small_square',
  },
  {
    name: 'black_medium_small_square',
  },
  {
    name: 'sunny',
  },
  {
    name: 'cloud',
  },
  {
    name: 'umbrella',
  },
  {
    name: 'snowman',
  },
  {
    name: 'comet',
  },
  {
    name: 'phone',
  },
  {
    name: 'telephone',
  },
  {
    name: 'ballot_box_with_check',
  },
  {
    name: 'umbrella_with_rain_drops',
  },
  {
    name: 'coffee',
  },
  {
    name: 'shamrock',
  },
  {
    name: 'point_up',
  },
  {
    name: 'skull_and_crossbones',
  },
  {
    name: 'radioactive_sign',
  },
  {
    name: 'biohazard_sign',
  },
  {
    name: 'orthodox_cross',
  },
  {
    name: 'star_and_crescent',
  },
  {
    name: 'peace_symbol',
  },
  {
    name: 'yin_yang',
  },
  {
    name: 'wheel_of_dharma',
  },
  {
    name: 'white_frowning_face',
  },
  {
    name: 'relaxed',
  },
  {
    name: 'female_sign',
  },
  {
    name: 'male_sign',
  },
  {
    name: 'aries',
  },
  {
    name: 'taurus',
  },
  {
    name: 'gemini',
  },
  {
    name: 'cancer',
  },
  {
    name: 'leo',
  },
  {
    name: 'virgo',
  },
  {
    name: 'libra',
  },
  {
    name: 'scorpius',
  },
  {
    name: 'sagittarius',
  },
  {
    name: 'capricorn',
  },
  {
    name: 'aquarius',
  },
  {
    name: 'pisces',
  },
  {
    name: 'chess_pawn',
  },
  {
    name: 'spades',
  },
  {
    name: 'clubs',
  },
  {
    name: 'hearts',
  },
  {
    name: 'diamonds',
  },
  {
    name: 'hotsprings',
  },
  {
    name: 'recycle',
  },
  {
    name: 'infinity',
  },
  {
    name: 'wheelchair',
  },
  {
    name: 'hammer_and_pick',
  },
  {
    name: 'anchor',
  },
  {
    name: 'crossed_swords',
  },
  {
    name: 'medical_symbol',
  },
  {
    name: 'staff_of_aesculapius',
  },
  {
    name: 'scales',
  },
  {
    name: 'alembic',
  },
  {
    name: 'gear',
  },
  {
    name: 'atom_symbol',
  },
  {
    name: 'fleur_de_lis',
  },
  {
    name: 'warning',
  },
  {
    name: 'zap',
  },
  {
    name: 'transgender_symbol',
  },
  {
    name: 'white_circle',
  },
  {
    name: 'black_circle',
  },
  {
    name: 'coffin',
  },
  {
    name: 'funeral_urn',
  },
  {
    name: 'soccer',
  },
  {
    name: 'baseball',
  },
  {
    name: 'snowman_without_snow',
  },
  {
    name: 'partly_sunny',
  },
  {
    name: 'thunder_cloud_and_rain',
  },
  {
    name: 'ophiuchus',
  },
  {
    name: 'pick',
  },
  {
    name: 'helmet_with_white_cross',
  },
  {
    name: 'chains',
  },
  {
    name: 'no_entry',
  },
  {
    name: 'shinto_shrine',
  },
  {
    name: 'church',
  },
  {
    name: 'mountain',
  },
  {
    name: 'umbrella_on_ground',
  },
  {
    name: 'fountain',
  },
  {
    name: 'golf',
  },
  {
    name: 'ferry',
  },
  {
    name: 'boat',
  },
  {
    name: 'sailboat',
  },
  {
    name: 'skier',
  },
  {
    name: 'ice_skate',
  },
  {
    name: 'woman-bouncing-ball',
  },
  {
    name: 'man-bouncing-ball',
  },
  {
    name: 'person_with_ball',
  },
  {
    name: 'tent',
  },
  {
    name: 'fuelpump',
  },
  {
    name: 'scissors',
  },
  {
    name: 'white_check_mark',
  },
  {
    name: 'airplane',
  },
  {
    name: 'email',
  },
  {
    name: 'envelope',
  },
  {
    name: 'fist',
  },
  {
    name: 'hand',
  },
  {
    name: 'raised_hand',
  },
  {
    name: 'v',
  },
  {
    name: 'writing_hand',
  },
  {
    name: 'pencil2',
  },
  {
    name: 'black_nib',
  },
  {
    name: 'heavy_check_mark',
  },
  {
    name: 'heavy_multiplication_x',
  },
  {
    name: 'latin_cross',
  },
  {
    name: 'star_of_david',
  },
  {
    name: 'sparkles',
  },
  {
    name: 'eight_spoked_asterisk',
  },
  {
    name: 'eight_pointed_black_star',
  },
  {
    name: 'snowflake',
  },
  {
    name: 'sparkle',
  },
  {
    name: 'x',
  },
  {
    name: 'negative_squared_cross_mark',
  },
  {
    name: 'question',
  },
  {
    name: 'grey_question',
  },
  {
    name: 'grey_exclamation',
  },
  {
    name: 'exclamation',
  },
  {
    name: 'heavy_exclamation_mark',
  },
  {
    name: 'heavy_heart_exclamation_mark_ornament',
  },
  {
    name: 'heart_on_fire',
  },
  {
    name: 'mending_heart',
  },
  {
    name: 'heart',
  },
  {
    name: 'heavy_plus_sign',
  },
  {
    name: 'heavy_minus_sign',
  },
  {
    name: 'heavy_division_sign',
  },
  {
    name: 'arrow_right',
  },
  {
    name: 'curly_loop',
  },
  {
    name: 'loop',
  },
  {
    name: 'arrow_heading_up',
  },
  {
    name: 'arrow_heading_down',
  },
  {
    name: 'arrow_left',
  },
  {
    name: 'arrow_up',
  },
  {
    name: 'arrow_down',
  },
  {
    name: 'black_large_square',
  },
  {
    name: 'white_large_square',
  },
  {
    name: 'star',
  },
  {
    name: 'o',
  },
  {
    name: 'wavy_dash',
  },
  {
    name: 'part_alternation_mark',
  },
  {
    name: 'congratulations',
  },
  {
    name: 'secret',
  },
]
