#!/command/with-contenv sh

set -eou pipefail

# serve the static files as an SPA
# proxy /api/* http calls to the backend

exec 2>&1
exec reproxy \
	--assets.location='/web/dist' \
	--assets.spa \
	--static.enabled \
	--static.rule='*,^/api/(.*),http://127.0.0.1:3000/$1,' \
	--gzip \
	--logger.stdout \
  --timeout.read-header=60s \
  --timeout.write=60s \
  --timeout.idle=60s \
  --timeout.dial=60s \
  --timeout.keep-alive=60s \
  --timeout.resp-header=60s \
  --timeout.idle-conn=90s \
  --max=0 \
	--listen="127.0.0.1:8080"
