import type { RouteRecordRaw } from 'vue-router'

// Public website imports

export const RoutesDocs: RouteRecordRaw[] = [
  {
    path: '/v1/download',
    name: 'download',
    redirect: { name: 'v2download' },
  },
  {
    path: '/download',
    alias: '/v2/download',
    component: () => import('./pages/download/DownloadV2Page.vue'),
    name: 'v2download',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/get-started/yc',
    component: () => import('./pages/LoginRegister.vue'),
    name: 'getStartedYC',
    meta: { nonApp: true, hideNavigation: true, isAuth: true },
    props: {
      startWithSignUp: true,
    },
  },
  {
    path: '/get-started/github',
    component: () => import('./pages/LoginRegister.vue'),
    name: 'getStartedGitHub',
    meta: { nonApp: true, hideNavigation: true, isAuth: true },
    props: {
      startWithSignUp: true,
    },
  },
  {
    path: '/about',
    component: () => import('./pages/docs/about/About.vue'),
    name: 'about',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/contact',
    component: () => import('./pages/docs/about/Contact.vue'),
    name: 'contact',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/v1/pricing',
    name: 'pricing',
    redirect: { name: 'v2pricing' },
  },
  {
    path: '/pricing',
    alias: '/v2/pricing',
    component: () => import('./pages/Pricing.vue'),
    name: 'v2pricing',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/security',
    component: () => import('./pages/docs/Security.vue'),
    name: 'resourcesSecurity',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/v1/docs',
    redirect: { name: 'v2DocsRoot' },
    name: 'resourcesDocs',
  },
  {
    path: '/kth',
    component: () => import('./components/campaigns/Kth.vue'),
    name: 'kth',
    meta: { nonApp: true },
  },
  {
    path: '/aoc',
    redirect: '/advent-of-code-2021-uoeIDQk',
    name: 'advent-of-code',
    meta: { nonApp: true },
  },
  {
    path: '/features/access-control',
    component: () => import('./pages/static/access-control/AccessControl.vue'),
    name: 'featuresAccessControl',
    meta: {
      nonApp: true,
    },
  },
  {
    path: '/features/instant-integration',
    component: () => import('./pages/static/instant-integration/InstantIntegration.vue'),
    name: 'featuresInstantIntegration',
    meta: {
      nonApp: true,
    },
  },
  {
    path: '/syncing',
    redirect: '/docs',
  },
  {
    path: '/docs/syncing',
    redirect: '/docs',
  },
  {
    path: '/features/instant-switching',
    component: () => import('./pages/docs/WorkspaceNavigation.vue'),
    name: 'featuresWorkspaceNavigation',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/features/integrations',
    component: () => import('./pages/docs/Integrations.vue'),
    name: 'featuresIntegrations',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/features/live',
    component: () => import('./pages/docs/LiveFeedback.vue'),
    name: 'featuresLiveFeedback',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/features/conflicts',
    component: () => import('./pages/docs/Conflicts.vue'),
    name: 'featuresConflicts',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/features/large-files',
    component: () => import('./pages/docs/LargeFiles.vue'),
    name: 'featuresLargeFiles',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/cli',
    component: () => import('./pages/docs/HelpSturdyCommandLine.vue'),
    name: 'resourcesHelpSturdyCommandLine',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/api',
    component: () => import('./pages/docs/API.vue'),
    name: 'resourcesApi',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/access-control',
    component: () => import('./pages/docs/access-control/AccessControl.vue'),
    name: 'docsAccessControl',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/suggestions',
    component: () => import('./pages/docs/suggestions/Suggestions.vue'),
    name: 'docsSuggestions',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/features/migrate-from-github',
    component: () => import('./pages/docs/MigrateFromGitHub.vue'),
    name: 'resourcesMigrateFromGitHub',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/continuous-integration',
    component: () => import('./pages/docs/continuous-integration/ContinuousIntegration.vue'),
    name: 'docsCICD',
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
    },
  },
  {
    path: '/blog/2022-05-03-this-week-at-sturdy-v1-8-0',
    name: 'blog2022-05-03-this-week-at-sturdy-v1-8-0',
    component: () => import('./pages/blog/v1-8-0/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#018 - This week at Sturdy – Sturdy v1.8.0!',
      blogDescription:
        "Hello world! In this newsletter we're sharing some of the biggest updates and new features in Sturdy v1.8, let's get started!",
      blogDate: 'May 3, 2022',
    },
  },
  {
    path: '/blog/2022-05-03-on-shipping-small-and-often',
    name: 'on-shipping-small-and-often',
    component: () => import('./pages/blog/2022-05-03/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#017 - What is stopping us from merging 30 pull requests per day?',
      blogDescription:
        'Most software projects are done by teams rather than individuals, so how we integrate work is critical. Collaborating on code is surprisingly challenging because any change made in isolation creates distance between developers. Shipping small and often is probably the most effective strategy for mitigating this. But just how frequently can we ship?',
      blogDate: 'May 3, 2022',
    },
  },
  {
    path: '/blog/2022-04-12-this-week-at-sturdy',
    name: 'blog2022-04-12',
    component: () => import('./pages/blog/2022-04-12/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#016 - This week at Sturdy',
      blogDescription:
        "Hello world! In this newsletter we're sharing some of the biggest updates and new features in Sturdy v1.7, let's get started!",
      blogDate: 'April 12, 2022',
    },
  },
  {
    path: '/blog/2022-03-10-introducing-draft-changes',
    name: 'blog2022-03-10',
    component: () => import('./pages/blog/2022-03-10/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#015 - Introducing Draft changes',
      blogDate: 'March 10, 2022',
      blogDescription:
        "Hey everyone! In this week's update I would like to share with you an update to the Sturdy workflow with Draft changes, as well as the release of Sturdy for Linux. Today is also an exciting day for us because we are launching Sturdy on Product Hunt!",
    },
  },
  {
    path: '/blog/2022-02-21-sturdy-is-now-open-source',
    name: 'blog2022-02-21',
    component: () => import('./pages/blog/2022-02-21/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#014 - Sturdy is now open-source',
      blogDate: 'February 21, 2022',
      blogDescription:
        'We have some really exciting news to share &mdash; Sturdy is now open-source! As developers, we love OSS, so to say that we are thrilled about this announcement would be an understatement!',
    },
  },
  {
    path: '/blog/2021-12-17-graphql-componentized-uis',
    name: 'graphql-componentized-uis',
    component: () => import('./pages/blog/graphql-componentized-uis/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#013 - GraphQL & Componentized UIs',
      blogDate: 'December 17, 2021',
      blogDescription:
        'GraphQL has become somewhat of an industry standard for APIs that are designed to be consumed by component-oriented UIs. Meanwhile, GraphQL client libraries have converged on strategies for maintaining a normalized cache of all parts of the graph that has been queried. This article proposes some patterns on how to maximize the utility and maintainability of frontend code using this stack.',
    },
  },
  {
    path: '/blog/2021-12-07-launching-the-sturdy-app',
    name: 'blog2021-12-07',
    component: () => import('./pages/blog/2021-12-07/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#012 - Launching the Sturdy App!',
      blogDate: 'December 7, 2021',
      blogDescription:
        'Hey! Here’s a summary of all of the latest and greatest features available in the latest version of Sturdy.',
    },
  },
  {
    path: '/blog/2021-11-29-scaling-teams',
    name: 'scaling-teams',
    component: () => import('./pages/blog/scaling-teams/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#011 - Scaling teams as parallel computing systems',
      blogDate: 'November 29, 2021',
      blogDescription:
        "Why team output doesn't scale linearly with team size? Teams are no different from a parallel computing systems. As such, they are subject to Amdahl's law, which governs their scalability.",
    },
  },
  {
    path: '/blog/2021-11-22-sturdy-the-app-is-coming',
    name: 'blog-2021-11-22',
    component: () => import('./pages/blog/2021-11-22/Post.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#010 - Sturdy-the-app is coming!',
      blogDate: 'November 22, 2021',
      blogDescription:
        'Hey! Here’s a summary of all of the latest and greatest features available in the latest version of Sturdy.',
    },
  },
  {
    path: '/blog/2021-09-29-acls-and-a-fresh-hot-look',
    name: 'blogRedesign',
    component: () => import('./pages/blog/redesign/Redesign.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#009 - ACLs and a fresh hot look!',
      blogDate: 'September 29, 2021',
      blogDescription:
        "Sturdy changelog. Sturdy now ships with Access Control Lists and a brand new interface, that's faster and more lightweight than ever.",
    },
  },
  {
    path: '/blog/2021-09-09-large-files',
    name: 'blogLargeFiles',
    component: () => import('./pages/blog/large-files/LargeFiles.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#008 - Large Files',
      blogDate: 'September 9, 2021',
      blogDescription:
        "Hey Sturdy-fans! Here's an update with all of the major changes since the last time we hit\n" +
        '      your inbox.',
    },
  },
  {
    path: '/blog/2021-08-18-unbreaking-code-collaboration',
    name: 'blogVision',
    component: () => import('./pages/blog/vision/Vision.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#007 - Unbreaking code collaboration',
      blogDate: 'August 18, 2021',
      blogDescription:
        "I feel like collaborating on code today is broken. It is too hard to get started and even after learning all the basic tools and commands there is just too much effort in making contributions as a team. Why is it so hard to give meaningful feedback on each other's code? How come the rest of the stack has evolved, when collaboration hasn't?",
    },
  },
  {
    path: '/blog/2021-08-12-signup-is-open',
    name: 'blogSignupIsOpen',
    component: () => import('./pages/blog/signup-is-open/SignupIsOpen.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#006 - Sturdy is here',
      blogDate: 'August 12, 2021',
      blogDescription:
        ' Making a new version control system is definitely not for the faint-hearted! It has taken us a lot of work to lay the foundation for the code collaboration platform that we are building.',
    },
  },
  {
    path: '/blog/2021-06-10-humane-code-review',
    name: 'blogHumaneCodeReview',
    component: () => import('./pages/blog/humane-code-review/HumaneCodeReview.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#005 - Humane Code Review',
      blogDate: 'June 10, 2021',
      blogDescription:
        'We’ve been thinking a lot about what it means to work on a team lately. Most often, developers are working on the same codebase, but are not really working together. More often than not the first time a teammate of your sees the code that you have written is when you’re considering the feature to be complete, and you’ve sent it for code review.',
    },
  },
  {
    path: '/blog/2021-05-06-importing-from-git',
    name: 'blogImportingFromGit',
    component: () => import('./pages/blog/import-from-git/ImportFromGit.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#004 - Importing from Git',
      blogDate: 'May 6, 2021',
      blogDescription:
        'Hey everyone! I hope that you’re doing great, and that May is treating you well!',
    },
  },
  {
    path: '/blog/2021-04-16-share-now',
    name: 'blogShareNow',
    component: () => import('./pages/blog/share-now/ShareNow.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#003 - Share Now!',
      blogDate: 'April 16, 2021',
      blogDescription:
        'Hey coders! As you’ve noticed, we’re still exploring the fundamentals to the core workflow of Sturdy. This week we’ve made some larger changes to when changes are copied from a workspace to a codebase. Let’s get into it!',
    },
  },
  {
    path: '/blog/2021-04-01-restore-to-any-point-in-time',
    name: 'blogRestoreToAnyPointInTime',
    component: () =>
      import('./pages/blog/restore-to-any-point-in-time/RestoreToAnyPointInTime.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#002 - Restore to any point in time',
      blogDate: 'April 1, 2021',
      blogDescription:
        'Hey everyone! This week we’ve been focusing on how Sturdy can help you if you make a mistake, or change your mind about what you’re building.',
    },
  },
  {
    path: '/blog/2021-03-24-yc-w21-demo-day',
    name: 'blogDemoDay',
    component: () => import('./pages/blog/yc-w21-demo-day/DemoDay.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#001 - YC W21 Demo Day!',
      blogDate: 'March 24, 2021',
      blogDescription:
        'The past week has been the culmination of our YC W21 batch, with Demo Day1 on Tuesday! A huge congratulations and thanks to all other companies in the batch!',
    },
  },
  {
    path: '/blog/2021-03-18-this-week-at-sturdy',
    name: 'blogThisWeekAtSturdy',
    component: () => import('./pages/blog/first-post/ThisWeekAtSturdy.vue'),
    meta: {
      nonApp: true,
      selfContainedLayout: true,
      neverElectron: true,
      blog: true,
      blogTitle: '#000 - This Week at Sturdy',
      blogDate: 'March 18, 2021',
      blogDescription:
        "Hey everyone! We've been working hard on Sturdy for the past few months, and as you might have seen, we've been making quite a lot of changes. I'm super excited about where we're going, and to be able to show of Sturdy and some of it's internals here in this post.",
    },
  },
  {
    path: '/blog',
    name: 'blog',
    component: () => import('./pages/blog/Blog.vue'),
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/careers',
    component: () => import('./pages/careers/Careers.vue'),
    name: 'careers',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/careers/founding-backend-engineer',
    redirect: '/careers',
  },
  {
    path: '/careers/founding-frontend-engineer',
    redirect: '/careers',
  },
  {
    path: '/careers/senior-backend-software-engineer',
    component: () => import('./pages/careers/SeniorBackendSoftwareEngineer.vue'),
    name: 'careersSeniorBackendSoftwareEngineer',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/careers/senior-frontend-software-engineer',
    component: () => import('./pages/careers/SeniorFrontendSoftwareEngineer.vue'),
    name: 'careersSeniorFrontendSoftwareEngineer',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/careers/full-stack-engineer',
    component: () => import('./pages/careers/FullStackEngineer.vue'),
    name: 'careersFullStackEngineer',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/',
    alias: '/v2',
    component: () => import('./pages/landing/Index.vue'),
    name: 'v2Index',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/v1/index',
    name: 'index',
    redirect: { name: 'v2Index' },
  },
  {
    path: '/docs',
    alias: '/v2/docs',
    component: () => import('./pages/docs/DocsRoot.vue'),
    name: 'v2DocsRoot',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/product-intro',
    alias: '/v2/docs/product-intro',
    component: () => import('./pages/docs/SturdyProductIntro.vue'),
    name: 'v2DocsProductIntro',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/how-sturdy-interacts-with-git',
    alias: ['/v2/docs/how-sturdy-interacts-with-git', '/docs/sturdy-for-git-users'],
    component: () => import('./pages/docs/HowSturdyInteractsWithGit.vue'),
    name: 'v2DocsHowSturdyInteractsWithGit',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/working-in-the-open',
    alias: '/v2/docs/working-in-the-open',
    component: () => import('./pages/docs/WorkingInTheOpen.vue'),
    name: 'v2DocsWorkingInTheOpen',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/how-to-ship-software-to-production',
    alias: '/v2/docs/how-to-ship-software-to-production',
    component: () => import('./pages/docs/HowToShipSoftwareToProduction.vue'),
    name: 'v2DocsHotToShipSoftwareToProduction',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/how-to-collaborate-with-others',
    alias: '/v2/docs/how-to-collaborate-with-others',
    component: () => import('./pages/docs/HowToCollaborateWithOthers.vue'),
    name: 'v2DocsHowToCollaborateWithOthers',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/how-to-edit-code',
    alias: '/v2/docs/how-to-edit-code',
    component: () => import('./pages/docs/HowToEditCode.vue'),
    name: 'v2DocsHowToEditCode',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/how-to-setup-sturdy-with-github',
    alias: '/v2/docs/how-to-setup-sturdy-with-github',
    component: () => import('./pages/docs/HowToSetupSturdyWithGithub.vue'),
    name: 'v2DocsHowToSetupSturdyWithGitHub',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/how-to-switch-between-tasks',
    alias: '/v2/docs/how-to-switch-between-tasks',
    component: () => import('./pages/docs/HowToSwitchBetweenTasks.vue'),
    name: 'v2DocsHowToSwitchBetweenTasks',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/quickstart',
    alias: '/v2/docs/quickstart',
    component: () => import('./pages/docs/QuickStart.vue'),
    name: 'v2DocsQuickStart',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/using-sturdy',
    alias: '/v2/docs/using-sturdy',
    component: () => import('./pages/docs/UsingSturdy.vue'),
    name: 'v2DocsUsingSturdy',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/pricing',
    alias: '/v2/docs/pricing',
    component: () => import('./pages/docs/Pricing.vue'),
    name: 'v2DocsPricing',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/index',
    alias: '/v2/docs/index',
    component: () => import('./pages/docs/Index.vue'),
    name: 'v2DocsIndex',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/self-hosted',
    alias: '/v2/docs/self-hosted',
    component: () => import('./pages/docs/SelfHosted.vue'),
    name: 'v2DocsSelfHosted',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/handbook/code-of-conduct',
    component: () => import('./pages/docs/handbook/CodeOfConduct.vue'),
    name: 'handbookCodeOfConduct',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/handbook/releases',
    component: () => import('./pages/docs/handbook/Releases.vue'),
    name: 'handbookReleases',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/handbook/contributions',
    component: () => import('./pages/docs/handbook/Contributions.vue'),
    name: 'handbookContributions',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/cli/install',
    component: () => import('./pages/docs/cli/Install.vue'),
    name: 'docsCliInstall',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/integrations/git',
    component: () => import('./pages/docs/git-integration/ConnectGit.vue'),
    name: 'docsIntegrationsGit',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/integrations/git/azure-devops',
    component: () => import('./pages/docs/git-integration/Azure.vue'),
    name: 'docsIntegrationsGitAzureDevops',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/docs/integrations/git/gitlab',
    component: () => import('./pages/docs/git-integration/GitLab.vue'),
    name: 'docsIntegrationsGitGitLab',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
  {
    path: '/roadmap',
    component: () => import('./pages/roadmap.vue'),
    name: 'docsRoadmap',
    meta: { nonApp: true, selfContainedLayout: true, neverElectron: true },
  },
]
